export {default as Header} from './Header/Header'
export {default as Slider} from './Slider/Slider'
export {default as Slide} from './Slider/Slide'
export {default as MiniCard} from './Scroller/MiniCard'
export {default as MegaCard} from './Scroller/MegaCard'
export {default as Scroller} from './Scroller/Scroller'
export {default as TradeSlider} from './TradeSlider/TradeSlider'
export {default as Categories} from './Categories/Categories'